stages:
  - whoami
  - run_robot_test
  - run_sitespeed

services:
  - docker:dind

whoami:
  stage: whoami
  script: whoami

run_robot_test:
  stage: run_robot_test
  script: docker restart robot-chrome-test

run_sitespeed:
  stage: run_sitespeed
  script: docker run --name sitespeed --network=eco-platform-analyzer_epa-network --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io http://front-vue:8080 -b firefox --graphite.host graphite --graphite.port 2003 --graphite.auth user:password --graphite.username guest --graphite.password guest
