concurrent = 1
check_interval = 0

[session_server]
    session_timeout = 1000

[[runners]]
    name = "z-green-web-ubuntu-runner"
    url = "https://gitlab.com/"
    token = "b3LBnAPjwDWQRseFzxdF"
    executor = "shell"
    [[runner.cache]]
        [runners.cache.s3]
        [runners.cache.gcs]