version: "3.3"

services:
  influxdb:
    image: ${INFLUXDB_IMAGE_VERSION}
    container_name: influxdb
    restart: always
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb2
      - ./influxdb/queries:/home/queries:rw
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG_NAME}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET_NAME}
      - DOCKER_INFLUXDB_INIT_RETENTION=${INFLUXDB_RETENTION}

  graphite:
    image: ${GRAPHITE_IMAGE_VERSION}
    container_name: graphite
    ports:
      - "2003:2003"
      - "8092:80"
    restart: always
    volumes:
      - graphite-storage:/opt/graphite/storage/whisper
      - ./graphite/conf/carbon.conf:/opt/graphite/conf/carbon.conf:ro
      
  powerapi-hwpc-sensor:
    image: ${POWER_API_HWPC_SENSOR_IMAGE_VERSION}
    container_name: powerapi-hwpc-sensor
    privileged: true
    volumes:
      - /sys:/sys
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /tmp/powerapi-sensor-reporting-firefox:/reporting
      - ./hwpc/config.json:/config.json:ro
    command: --config-file /config.json
    profiles:
      - preconso

  smartwatts:
    build: ./powerapi
    container_name: smartwatts
    depends_on:
      - influxdb
      - powerapi-hwpc-sensor
    command: --config-file /config.json
    profiles:
      - preconso
    volumes:
      - ./smartwatts/config.json:/config.json:ro

  selenium-hub:
    image: ${SELENIUM_HUB_IMAGE_VERSION}
    container_name: selenium-hub
    expose:
      - 4444    
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    profiles:
      - preconso

  chrome:
    image: ${SELENIUM_NODE_CHROME_IMAGE_VERSION}
    container_name: selenium-node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
    profiles:
      - preconso

  robot-chrome-test:
    build: robot
    command: -v BROWSER:gc --outputdir /out /tests/*.robot
    container_name: robot-chrome-test
    volumes:
      - ./robot/tests:/tests:ro
      - ./robot-results/gc:/out:rw
    profiles:
      - conso

  eco-index:
    build: eco-index
    container_name: eco-index
    depends_on:
      - influxdb
    command: greenit analyse input/urls.yaml -f influxdb --ci --influxdb_hostname http://${INFLUXDB_HOST}:${INFLUXDB_PORT} --influxdb_token ${INFLUXDB_TOKEN} --influxdb_bucket ${INFLUXDB_BUCKET_NAME} --influxdb_org=${INFLUXDB_ORG_NAME}
    volumes:
      - tmp-storage:/app/input:ro
      - ./eco-index/results:/app/output:rw
    environment:
      - TZ:Europe/Paris
    profiles:
      - test

  sitespeed:
    container_name: sitespeed
    image: ${SITESPEED_IMAGE_VERSION}
    shm_size: '1g'
    depends_on:
      - graphite
    command: /input/urls.txt --cpu --sustainable.enable --axe.enable -b chrome --chrome.args no-sandbox --graphite.host graphite --graphite.webHost http://graphite --graphite.port ${GRAPHITE_PORT} --graphite.httpPort 8092 --graphite.auth user:password --graphite.username ${GRAPHITE_USERNAME} --graphite.password ${GRAPHITE_PASSWORD}
    volumes:
      - ./sitespeed/results:/sitespeed.io/sitespeed-result:rw
      - tmp-storage:/input:ro
    profiles:
      - test
  
  yellowlabtools:
    container_name: yellowlabtools
    build:
      context: yellowLabTools/src
    command: /input/urls-yellowlabtools.yaml --reporter influxdb --influxdb-hostname ${INFLUXDB_HOST} --influxdb-port ${INFLUXDB_PORT} --influxdb-org ${INFLUXDB_ORG_NAME} --influxdb-token ${INFLUXDB_TOKEN} --influxdb-bucket ${INFLUXDB_BUCKET_NAME} --influxdb-offenders
    user: "${RUNNER_USER_ID}:${RUNNER_GROUP_ID}"
    volumes:
      - tmp-storage:/input
      - ./yellowLabTools/reports:/usr/src/ylt/results:rw
    privileged: true
    profiles:
      - test

  grafana:
    container_name: grafana
    image: ${GRAFANA_IMAGE_VERSION}
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
      - graphite
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - INFLUXDB_ORG_ID=${INFLUXDB_ORG_ID}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_BUCKET_NAME=${INFLUXDB_BUCKET_NAME}
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_PORT=${INFLUXDB_PORT}
      - GRAPHITE_PORT=${GRAPHITE_ACCESS_PORT}
      - GRAPHITE_HOST=${GRAPHITE_HOST}
      - GRAPHITE_USERNAME=${GRAPHITE_USERNAME}
      - GRAPHITE_PASSWORD=${GRAPHITE_PASSWORD}

  grafana-setup:
    container_name: grafana_setup
    image: ${GRAFANA_SETUP_IMAGE_VERSION}
    links:
      - grafana
    environment:
      - GF_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USER=${GRAFANA_USERNAME}
    profiles:
      - setup
  
  url-converter:
    container_name: url-converter
    build: ./input/url-file-converter
    command: /home/urlconverter/urls.yaml /home/urlconverter/results/urls.yaml /home/urlconverter/results/urls.txt /home/urlconverter/results/urls-yellowlabtools.yaml /home/urlconverter/tests/
    volumes: 
      - ./input/urls.yaml:/home/urlconverter/urls.yaml:ro
      - tmp-storage:/home/urlconverter/results:rw
      - ./input/templates/:/home/urlconverter/templates/:ro
      - ./robot/tests/:/home/urlconverter/tests/:rw
    profiles:
      - pretest

  report:
    container_name: report
    build: ./reports
    environment:
      - INFLUXDB_ORG_NAME=${INFLUXDB_ORG_NAME}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_BUCKET_NAME=${INFLUXDB_BUCKET_NAME}
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_PORT=${INFLUXDB_PORT}
      - GRAPHITE_PORT=${GRAPHITE_ACCESS_PORT}
      - GRAPHITE_HOST=${GRAPHITE_HOST}
      - GRAPHITE_USERNAME=${GRAPHITE_USERNAME}
      - GRAPHITE_PASSWORD=${GRAPHITE_PASSWORD}
    volumes:
      - ./reports/reports:/opt/report/results/:rw
      - ./input/urls.yaml:/opt/report/urls.yaml:ro
      - ./yellowLabTools/reports:/opt/report/offenders:ro
    profiles:
      - report

volumes:
  influxdb-storage:
  graphite-storage:
  report-storage:
  grafana-storage:
  tmp-storage: