version: "3.3"

services:
  report-test:
    container_name: report-test
    build:
      context: reports/
      dockerfile: Dockerfile-test
    environment:
      - INFLUXDB_ORG_NAME=${INFLUXDB_ORG_NAME}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_BUCKET_NAME=${INFLUXDB_BUCKET_NAME}
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_PORT=${INFLUXDB_PORT}
