version: '3.3'

services:
   db:
     container_name: wordpress_db
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     networks:
       - epa-network      

   wordpress:
     container_name: wordpress
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "9092:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     networks:
       - epa-network       
volumes:
    db_data: {}
networks:
    epa-network:    