{
 "title": "Sitespeed page metrics",
 "time": { "from": "2022-07-22T22:11:52.768Z", "to": "2022-09-24T22:11:52.832Z" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "domain",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: v.defaultBucket,\n    tag: \"group\",\n    start: -1y\n)"
   },
   {
    "name": "page",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: v.defaultBucket,\n    tag: \"page\",\n    predicate: (r) => r.group == ${group:doublequote},\n    start: -1y\n)"
   },
   {
    "name": "browser",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: v.defaultBucket,\n    tag: \"browser\", predicate: (r) => r.page == ${page:doublequote} and r.group == ${group:doublequote},\n    start: -1y\n)"
   },
   {
    "name": "connectivity",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: v.defaultBucket,\n    tag: \"connectivity\",\n    tag: \"browser\", predicate: (r) => r.page == ${page:doublequote} and r.group == ${group:doublequote},\n    start: -1y\n)"
   },
   {
    "name": "function",
    "query": "min, mean,median,p90,max,stddev"
   }
  ]
 },
 "panels": [
  {
   "title": "Page metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Visual Metrics [$function]",
     "type": "timeseries",
     "gridPos": { "h": 24, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"ttfb\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> set(key: \"_field\", value: \"mem_total\")\n"
      },
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"FirstVisualChange\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      },
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"LastVisualChange\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      },
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"SpeedIndex\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      },
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"fullyLoaded\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    },
    {
     "title": "Page Vitals",
     "type": "text",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Transfer Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"transferSize\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => not exists r[\"contentType\"])\n    |> filter(fn: (r) => not exists r[\"party\"])\n    |> last()"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"requests\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> filter(fn: (r) => not exists r[\"contentType\"])\n    |> filter(fn: (r) => not exists r[\"party\"])\n    |> last()"
      }
     ]
    },
    {
     "title": "DOM elements",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"domElements\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Google Web Vitals",
     "type": "text",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {}
     ]
    },
    {
     "title": "First Contentful Paint",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"first-contentful-paint\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Largest Contentful Paint",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"largestContentfulPaint\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Cumulative Layout Shift",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"cumulativeLayoutShift\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Total Blocking Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"totalBlockingTime\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Coach Score",
     "type": "text",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Best Practice",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"origin\"] == \"coach\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"advice\"] == \"bestpractice\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Performance",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"origin\"] == \"coach\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"advice\"] == \"performance\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Privacy",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"origin\"] == \"coach\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"advice\"] == \"privacy\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"origin\"] == \"coach\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => not exists r[\"advice\"])\n    |> last()"
      }
     ]
    },
    {
     "title": "Axe violations [enable with --axe.enable]",
     "type": "text",
     "gridPos": { "h": 1, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Minor",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"origin\"] == \"axe\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"_measurement\"] == \"minor\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Moderate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"origin\"] == \"axe\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"_measurement\"] == \"moderate\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Serious",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"origin\"] == \"axe\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"_measurement\"] == \"serious\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Critical",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"origin\"] == \"axe\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"_measurement\"] == \"critical\")\n    |> last()"
      }
     ]
    }
   ]
  },
  {
   "title": "Size history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTML size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"transferSize\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"contentType\"] == \"html\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      },
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"contentSize\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"contentType\"] == \"html\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    },
    {
     "title": "Javascript size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"transferSize\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"contentType\"] == \"javascript\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      },
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"contentSize\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"contentType\"] == \"html\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    },
    {
     "title": "CSS size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"transferSize\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"contentType\"] == \"css\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      },
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"contentSize\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"contentType\"] == \"html\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    },
    {
     "title": "Image size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"contentSize\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"contentType\"] == \"html\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    },
    {
     "title": "Content size per type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"contentSize\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    },
    {
     "title": "Transfer size per type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"transferSize\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Coach history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Coach Score",
     "type": "timeseries",
     "description": "The performance score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using performance best practices.The performance score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using performance best practices.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"score\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"origin\"] == \"coach\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Axe history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Axe violations",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"origin\"] == \"axe\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Google Web Vitals trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "First Contentful Paint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n  |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"_measurement\"] == \"ttfb\")"
      }
     ]
    },
    {
     "title": "Largest Contentful Paint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"_measurement\"] == \"largestContentfulPaint\")"
      }
     ]
    },
    {
     "title": "Total Blocking Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"_measurement\"] == \"totalBlockingTime\")"
      }
     ]
    },
    {
     "title": "Cumulative Layout Shift",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"_measurement\"] == \"cumulativeLayoutShift\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Google Web Vitals history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "First Contentful Paint (FCP)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"first-contentful-paint\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Cumulative Layout Shift (CLS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"cumulativeLayoutShift\")\n    |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    },
    {
     "title": "Largest Contentful Paint (LCP)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"largestContentfulPaint\")\n    |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    },
    {
     "title": "Total Blocking Time (TBT)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"totalBlockingTime\")\n    |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Navigation Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Navigation Timings  [$function]",
     "type": "timeseries",
     "description": "Metrics collected from theNavigation Timing API",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"navigationTiming\"] != \"\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Page statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Document Height",
     "type": "stat",
     "description": "The document height in pixels.",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"documentHeight\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Number of iframe",
     "type": "stat",
     "description": "The total number of iframes used on the page.",
     "gridPos": { "h": 4, "w": 4, "x": 11, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"iframes\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Number of Domain",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 15, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"totalDomains\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Number of Cookies",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"cookies\")\n    |> filter(fn: (r) => r[\"origin\"] == \"thirdparty\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Expire Cache Time",
     "type": "stat",
     "description": "The $function cache expire time of all responses for the page.",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"expireStats\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Last Modified Time",
     "type": "stat",
     "description": "The $function last modified time of all responses for the page.",
     "gridPos": { "h": 4, "w": 4, "x": 5, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"lastModifiedStats\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Average DOM Depth",
     "type": "stat",
     "description": "The average DOM depth of the page.",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"domDepth\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"avg\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Max DOM Depth",
     "type": "stat",
     "description": "The max depth of DOM elements on the page.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"domDepth\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"max\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Local Storage Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"localStorageSize\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> last()"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Long Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Long Task",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"tasks\")\n    |> filter(fn: (r) => r[\"cpu\"] == \"longTask\")\n    |> filter(fn: (r) => r[\"longTasks\"] == \"tasks\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Number of Long Task Before FCP",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 5, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"tasks\")\n    |> filter(fn: (r) => r[\"cpu\"] == \"longTask\")\n    |> filter(fn: (r) => r[\"longTasks\"] == \"beforeFirstContentfulPaint\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Total Blocking Time",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 11, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"totalBlockingTime\")\n    |> filter(fn: (r) => r[\"cpu\"] == \"longTask\")\n    |> filter(fn: (r) => r[\"longTasks\"] == \"totalBlockingTime\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
      }
     ]
    },
    {
     "title": "Longest Long Task",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"durations\")\n    |> filter(fn: (r) => r[\"cpu\"] == \"longTask\")\n    |> filter(fn: (r) => r[\"longTasks\"] == \"durations\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
      }
     ]
    },
    {
     "title": "CPU Long Tasks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"totalBlockingTime\")\n    |> filter(fn: (r) => r[\"cpu\"] == \"longTask\")\n    |> filter(fn: (r) => r[\"longTasks\"] == \"totalBlockingTime\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    },
    {
     "title": "CPU Long Tasks Before FCP",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 5, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"tasks\")\n    |> filter(fn: (r) => r[\"cpu\"] == \"longTask\")\n    |> filter(fn: (r) => r[\"longTasks\"] == \"beforeFirstContentfulPaint\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    },
    {
     "title": "Total Blocking Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 11, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"totalBlockingTime\")\n    |> filter(fn: (r) => r[\"cpu\"] == \"longTask\")\n    |> filter(fn: (r) => r[\"longTasks\"] == \"totalBlockingTime\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    },
    {
     "title": "Longest Long Task",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"durations\")\n    |> filter(fn: (r) => r[\"cpu\"] == \"longTask\")\n    |> filter(fn: (r) => r[\"longTasks\"] == \"durations\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Carbon emission (enable with --sustainable.enable)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"origin\"] == \"sustainable\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
      }
     ]
    }
   ]
  },
  {
   "title": "Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timings  [$function]",
     "type": "timeseries",
     "description": "Timing metrics collected using browser APIs like the Navigation Timing API.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"fullyLoaded\" or r[\"_measurement\"] == \"firstPaint\" or r[\"_measurement\"] == \"loadEventEnd\" or r[\"_measurement\"] == \"domContentLoadedTime\" or r[\"_measurement\"] == \"serverResponseTime\")\n    |> filter(fn: (r) => r[\"origin\"] == \"browsertime\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
      }
     ]
    }
   ]
  },
  {
   "title": "Main document timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Main document timings [$function]",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"_queued\" or r[\"_measurement\"] == \"connect\" or r[\"_measurement\"] == \"blocked\" or r[\"_measurement\"] == \"dns\" or r[\"_measurement\"] == \"receive\" or r[\"_measurement\"] == \"send\" or r[\"_measurement\"] == \"ssl\" or r[\"_measurement\"] == \"wait\")\n    |> filter(fn: (r) => r[\"origin\"] == \"browsertime\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
      }
     ]
    }
   ]
  },
  {
   "title": "Cookies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cookies",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"cookies\")\n    |> filter(fn: (r) => r[\"party\"] != \"\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${page}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"value\")\n    |> last()"
      }
     ]
    }
   ]
  }
 ]
}