{
 "title": "Pagiel summary",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pagename",
    "label": "Nom de la page",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: v.defaultBucket,\n    tag: \"pageName\",\n    start: -1y\n)\n"
   },
   {
    "name": "group",
    "label": "domain",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: v.defaultBucket,\n    tag: \"group\",\n    start: -1y\n)"
   },
   {
    "name": "browser",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: v.defaultBucket,\n    tag: \"browser\", predicate: (r) => r.page == ${page:doublequote} and r.group == ${group:doublequote},\n    start: -1y\n)"
   },
   {
    "name": "connectivity",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: v.defaultBucket,\n    tag: \"connectivity\",\n    tag: \"browser\", predicate: (r) => r.page == ${page:doublequote} and r.group == ${group:doublequote},\n    start: -1y\n)"
   },
   {
    "name": "function",
    "query": "min, mean,median,p90,max,stddev"
   }
  ]
 },
 "panels": [
  { "title": "GreenIT Analysis metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eco_index",
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.pageName == \"${pagename}\" and r._field == \"ecoindex\")\n    |> last()",
     "select": [
      [
       { "params": [ "EcoIndex" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.pageName == \"${pagename}\" and r._field == \"grade\")\n    |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 8, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eco_index",
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.pageName == \"${pagename}\" and r._field == \"ecoindex\")\n    |> last()",
     "select": [
      [
       { "params": [ "EcoIndex" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.pageName == \"${pagename}\" and r._field == \"domSize\")\n    |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 8, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.pageName == \"${pagename}\" and r._field == \"domSize\")\n    |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.pageName == \"${pagename}\" and r._field == \"responsesSize\")\n    |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.pageName == \"${pagename}\" and r._field == \"responsesSizeUncompress\")\n    |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 8, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.pageName == \"${pagename}\" and r._field == \"responsesSize\")\n    |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.pageName == \"${pagename}\" and r._field == \"nbRequest\")\n    |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 8, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.pageName == \"${pagename}\" and r._field == \"nbRequest\")\n    |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Sitespeed metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Visual Metrics [$function]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"ttfb\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> set(key: \"_field\", value: \"mem_total\")\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"FirstVisualChange\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"LastVisualChange\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"SpeedIndex\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"fullyLoaded\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"cumulativeLayoutShift\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"largestContentfulPaint\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n    |> last()"
    }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"first-contentful-paint\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
    }
   ]
  },
  {
   "title": "First visual change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"FirstVisualChange\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${pagename}\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Last visual change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"LastVisualChange\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Fully loaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"fullyLoaded\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Total Blocking Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"totalBlockingTime\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Time to 1st Byte",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"ttfb\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Speed Index",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"SpeedIndex\")\n    |> filter(fn: (r) => r[\"group\"] == \"${group}\")\n    |> filter(fn: (r) => r[\"page\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"${function}\")\n    |> last()"
    }
   ]
  }
 ]
}