{
 "title": "YellowLabTools",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pagename",
    "label": "Nom de la page",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: v.defaultBucket,\n    tag: \"name\",\n    start: -1y\n)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume de fichier CSS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"cssSize\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Nombre de fichier CSS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"cssCount\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Breakpoint CSS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"cssBreakpoints\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Style CSS inline",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"cssInlineStyles\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Règles CSS mobile first",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"cssMobileFirst\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Erreurs de parsing CSS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"cssParsingErrors\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Volume de fichier CSS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"smallCssFiles\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Volume de fichier CSS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"cssSize\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Modification du DOM en js",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"DOMaccesses\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Nombre d'iframes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"iframesCount\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Nombre d'éléments du DOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"DOMelementsCount\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Profondeur max du DOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"DOMelementMaxDepth\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Id dupliqué dans le DOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"DOMidDuplicated\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Image sous la ligne de navigation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"lazyLoadableImagesBelowTheFold\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Nombre total de requête",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"totalRequests\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Nombre de domaines requêtés",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"domains\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Nombre de 404 reçu ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"notFound\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Fichier identiques chargé depuis des sources différentes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"identicalFiles\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Nombre de requête dont la réponse est vide",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"emptyRequests\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Image avec un display:none",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"hiddenImages\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Nombre de listener sur l'evenement \"scroll\"",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"eventsScrollBound\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Durée d'execution du script (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"scriptDuration\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Erreurs lors de l'execution du js",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"jsErrors\")\n    |> last()"
    }
   ]
  },
  {
   "title": "appel a document.write",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"documentWriteCalls\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Requetes AJAX synchrone",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"synchronousXHR\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Fichiers dont le cache n'est pa sspécifié",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"cachingNotSpecified\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Fichier dont le cache est désactivé",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"cachingDisabled\")\n    |> last()"
    }
   ]
  },
  {
   "title": "Fichier dont le cache est court",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"YellowLabtools\")\n    |> filter(fn: (r) => r[\"name\"] == \"${pagename}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"cachingTooShort\")\n    |> last()"
    }
   ]
  }
 ]
}