{{- if .Values.ingress.enabled -}}
{{- $fullName := include "defaults.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "defaults.labels" . | nindent 4 }}
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: 'true'
    {{- if .Values.ingress.tlsSecretNamespace }}
    projectcontour.io/tls-cert-namespace: {{ .Values.ingress.tlsSecretNamespace }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }} 
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  number: {{ $svcPort }}
{{- end }}
