{{ if .Values.deployment.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "defaults.fullname" . }}}
  labels:
    {{- include "defaults.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Génération automatique des clé/valeurs à partir des Values
    {{- range $key, $value := .Values.deployment.secrets }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
{{- end }}

